### ISSUE TITLE
Grails 2.1.1 + Activiti Plugin 5.9 = unresolved dependency 'org.springframework#spring-test;3.1.2.RELEASE'

### ISSUE THREAD

**Issue by Unisay** [limcheekin/activiti#11]
:::: WARNINGS
        ::::::::::::::::::::::::::::::::::::::::::::::
        ::          UNRESOLVED DEPENDENCIES         ::
        ::::::::::::::::::::::::::::::::::::::::::::::
        :: org.springframework#spring-test;3.1.2.RELEASE: configuration not found in org.springframework#spring-test;3.1.2.RELEASE: 'master'. It was required from org.grails.internal#businesspartner;0.1 test
        ::::::::::::::::::::::::::::::::::::::::::::::

| Error Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):

**Comment by Unisay** [comment]
After adding 
    dependencies {
        compile ('org.activiti:activiti-engine:5.10') {
            excludes 'livetribe-jsr223'
        }
        runtime 'org.activiti:activiti-spring:5.10'
    }
to the BuildConfig.groovy 
problem with spring versions mismatch is gone (activiti 5.10 uses the same version of spring 3.1.2 as Grails 2.1.1 does)

**Comment by limcheekin** [comment]
Thanks for reporting this issue. I will upgrade and release activiti plugin 5.10 asap.

**Comment by lovenomuch** [comment]
Can you please publish this to grails plugin repository? Thanks.
