### ISSUE TITLE
Issue installing 5.9

### ISSUE THREAD

**Issue by ghost** [limcheekin/activiti#8]
I get the following error trying to install the activiti plugin. This may have to do with the dependencies.
| Loading Grails 2.1.0
| Configuring classpath
| Error Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):
- org.activiti:activiti-engine:5.9
- org.activiti:activiti-spring:5.9

IDEA hook: Grails not found!
| Error java.lang.NullPointerException
| Error     at org.jetbrains.groovy.grails.rt.Agent$2.run(Agent.java:99)
| Error     at java.lang.Thread.run(Thread.java:722)

**Comment by limcheekin** [comment]
Thanks for report the issue. Did you tried to run the command in console instead of IDEA?

**Comment by ghost** [comment]
Adding mavenRepo "https://maven.alfresco.com/nexus/content/groups/public/" to BuildConfig.groovy seems to have resolved the issue.

**Comment by limcheekin** [comment]
Yeah, you need to specify the custom repository as per document at http://grails.org/plugin/activiti
